# Generated by Django 3.2.5 on 2021-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirm_num', models.CharField(max_length=16)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
