# Generated by Django 3.2.5 on 2021-07-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_sales_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='slider/image/')),
                ('url', models.URLField(blank=True, help_text='Leave this field blank if you have selected a category', verbose_name='Set url for slider')),
                ('category', models.ForeignKey(blank=True, help_text='Leave this field blank if you have selected a url', on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Set category for slider')),
            ],
        ),
    ]
