# Generated by Django 3.2.5 on 2021-11-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave this field blank if you have selected a url', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Set category for slider'),
        ),
    ]
