# Generated by Django 3.2.3 on 2021-06-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
    ]
