# Generated by Django 3.2.3 on 2021-06-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
