# Generated by Django 3.2.5 on 2021-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
